### PR TITLE
typescript error - ioredis has no default export #6

### PR DESCRIPTION
**Pull request by regevbr**
typescript error - ioredis has no default export #6

### CODE REVIEW

**Comment by regevbr** [comment]
@dex4er can you please code review it?

**Comment by dex4er** [comment]
Hi.

Can't you use `"esModuleInterop": true` option in your `tsconfig.json`? I would prefer to stay with ES7 syntax for `import` and Typescript >= 2.7 supports it with this option.

**Comment by dex4er** [comment]
In other way: if it doesn't break any setup with or without `esModuleInterop` or `allowSyntheticDefaultImports` then I can change it.

**Comment by regevbr** [comment]
you are using `esModuleInterop` in your tsconfig file, and I'm not using it and the only thing that breaks on my end is the discussed import, so as I understand it, my change won't break any system...
Also, according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import the syntax you are using is only for modules with default exports which `ioredis` does not have...
also, adding `esModuleInterop` causes an addition of boilerplate code to handle those cases and I hate using any typescript features that create boilerplate code...
What do you think?

**Comment by dex4er** [comment]
I think it is not so simple. You can import modules without `default` symbol with webpack already and this option is some kind of workaround for nodejs vs typescript incompatibility.

And there is `import fs from 'fs'` vs `import fs as * from 'fs'` vs `import fs = require('fs')` and it gives me a real headache. Probably `esModuleInterop` is a right way to make some standarization for this mess.

You can check this discussion: https://github.com/tilfin/readline-transform/pull/2

But for us it means that sliding-window-rate-limiter can work with and without `esModuleInterop` so I can accept this patch.

**Pull request merged**
